### ISSUE TITLE
Error compiling project after upgrading to 1.2.1

### ISSUE THREAD

**Issue by navinpeiris** [voltone/aws_rds_castore#12]
After upgrading to v1.2.1, I get the following error when trying to compile the dep in an Elixir project:

```
❯ mix compile
==> aws_rds_castore
Compiling 1 file (.erl)
src/aws_rds_castore.erl:10:15: Warning: code:lib_dir/2 is deprecated; this functionality will be removed in a future release
%   10|     PrivDir = code:lib_dir(aws_rds_castore, priv),
%     |               ^

Compiling 2 files (.ex)

== Compilation error in file lib/mix/tasks/aws_rds_castore/certdata.ex ==
** (ArgumentError) lib file public_key/include/OTP-PUB-KEY.hrl could not be found
    (elixir 1.17.3) lib/record/extractor.ex:41: Record.Extractor.from_lib_file/1
    (elixir 1.17.3) lib/record/extractor.ex:18: Record.Extractor.from_or_from_lib_file/1
    (elixir 1.17.3) lib/record/extractor.ex:5: Record.Extractor.extract/2
    lib/mix/tasks/aws_rds_castore/certdata.ex:29: (module)
```

Current workaround is to downgrade to v1.2.0

**Comment by navinpeiris** [comment]
Thanks @voltone 🫶

**Comment by voltone** [comment]
Just pushed v1.2.2
